/**
 * Submission-package domain logic, pure and unit-tested. Given the extracted
 * compliance matrix, the company profile, and which documents the platform
 * generates, it resolves each requirement to a status + artifact, assembles an
 * ordered manifest, and validates the package before submission.
 */
import type {
  ComplianceRequirement,
  ResolvedRequirement,
  PackageItem,
  PackageValidation,
  RequirementCategory,
  AuditFinding,
} from "../types";

/** documents.kind values used for generated package artifacts. */
export const ARTIFACT_KIND = {
  coverLetter: "cover_letter",
  pricingSchedule: "pricing_schedule",
  repsCerts: "reps_certs",
  capability: "capability_statement",
  bidPdf: "bid_pdf",
  complianceChecklist: "compliance_checklist",
  amendmentAck: "amendment_ack",
} as const;

/**
 * Every stable identity one requirement can be recognised by.
 *
 * The compliance matrix is regenerated by a language model on every
 * re-analysis, and the `id` is a slug the model invents each time. Re-reading
 * a solicitation after an amendment could turn "sf1449" into "sf_1449" or
 * "signed_sf1449", and every "I signed and uploaded this" confirmation keyed
 * to the old slug stopped matching: the operator's completed, signed forms
 * silently reverted to outstanding and the package refused to submit, hours
 * before a deadline, with no indication why.
 *
 * Matching on the official form number and on the normalized title as well
 * means a requirement stays the same requirement even when its slug moves.
 */
export function requirementKeys(req: {
  id?: string;
  title?: string;
  official_form?: string;
}): string[] {
  const keys: string[] = [];
  const id = req.id?.trim();
  if (id) {
    keys.push(id);
    keys.push(`id:${id.replace(/[^a-z0-9]+/gi, "").toLowerCase()}`);
  }
  const form = req.official_form?.trim();
  if (form) keys.push(`form:${form.replace(/[^a-z0-9]+/gi, "").toLowerCase()}`);
  const title = req.title?.trim();
  if (title) {
    // Word set, not the raw string: "Signed SF-1449 offer form" and "SF-1449
    // offer form, signed" are the same requirement written two ways.
    const words = title
      .toLowerCase()
      .replace(/[^a-z0-9\s]+/g, " ")
      .split(/\s+/)
      .filter((w) => w && !TITLE_NOISE.has(w));
    if (words.length) keys.push(`title:${[...new Set(words)].sort().join("-")}`);
  }
  return keys;
}

const TITLE_NOISE = new Set([
  "the", "a", "an", "and", "of", "for", "to", "with", "in", "on",
  "signed", "sign", "completed", "complete", "copy", "copies", "form", "forms",
  "document", "documents", "attachment", "attached", "required", "submit",
]);

/**
 * Build the confirmation lookup from the previously stored matrix. Keys from
 * every identity a confirmed requirement had, so the next resolve recognises
 * it however the model renamed it.
 */
export function confirmedKeys(
  prior: { id?: string; title?: string; official_form?: string; operator_confirmed?: boolean }[]
): Set<string> {
  const set = new Set<string>();
  for (const r of prior) {
    if (!r.operator_confirmed) continue;
    for (const k of requirementKeys(r)) set.add(k);
  }
  return set;
}

export interface ResolveContext {
  /**
   * Identity keys (see requirementKeys) of requirements the operator already
   * confirmed complete. Raw ids are accepted too, so a caller holding plain
   * ids keeps working.
   */
  confirmed: Set<string>;
  /** True when a past-performance / technical narrative was generated. */
  hasNarrative: boolean;
  /** Key company identifiers present (UEI/CAGE), affects reps&certs warnings. */
  hasIdentifiers: boolean;
}

/**
 * Which document the platform can produce for a requirement.
 *
 * WHAT the requirement is decides this, not who is expected to satisfy it.
 * Keying off satisfied_by put the wrong document in real packages: a signed
 * bid schedule (category "pricing", satisfied_by "operator_signature") fell
 * through to the reps and certs sheet, so the agency received a certifications
 * data sheet named "Signed bid schedule" and no price document at all. A
 * signed transmittal letter landed on the same sheet, giving two manifest
 * items pointing at one file under two authoritative names.
 *
 * A generated document is only ever offered for a category the platform can
 * genuinely produce. Supporting attachments (insurance certificates, licences,
 * bonds) are the operator's: we cannot generate a certificate of insurance,
 * and pretending otherwise shipped a capability statement in its place.
 */
function artifactFor(req: ComplianceRequirement): string {
  if (req.category === "acknowledgment") return ARTIFACT_KIND.amendmentAck;
  if (req.category === "pricing") return ARTIFACT_KIND.pricingSchedule;
  if (req.category === "certification" || req.category === "form")
    return ARTIFACT_KIND.repsCerts;
  // A capability statement is a real thing we build, but only when that is
  // what was asked for.
  if (/capabilit/i.test(req.title)) return ARTIFACT_KIND.capability;
  // Narrative splits in two. The transmittal letter we generate, and it is a
  // transmittal letter: a page that says here is our offer. A technical
  // approach, management plan, quality control plan or past-performance
  // volume is a written response to this solicitation's evaluation factors,
  // frequently page-limited and scored. Handing the agency a cover letter in
  // its place is not a near miss, it is an unresponsive proposal that reads
  // as complete on our side. Anything that is not recognisably the letter
  // itself belongs to the operator.
  if (req.category === "narrative" && COVER_LETTER_RE.test(req.title))
    return ARTIFACT_KIND.coverLetter;
  return ""; // volumes, attachments, other: only the operator can supply it
}

const COVER_LETTER_RE =
  /\b(cover|transmittal|submittal|submission|offer|bid|proposal)\s+letter\b|\bletter\s+of\s+(transmittal|submittal|submission|intent|interest)\b|^\s*letter\b/i;

/**
 * Format rules the platform cannot guarantee it has met.
 *
 * `format` carries the solicitation's own words: "10 pages maximum, 12 point
 * Times New Roman", "four hard copies, tabbed", "submit on the agency's Excel
 * worksheet". These were captured during analysis and then never read again,
 * so a page-limited volume could be marked satisfied by a generated PDF
 * nobody had counted the pages of, and a required Excel worksheet was
 * answered with a PDF. Anything matched here needs a person to check the
 * document against the rule before the package goes out; the rule is quoted
 * back verbatim so they can.
 */
export function unmetFormatRule(format?: string | null): string | null {
  const f = (format ?? "").trim();
  if (!f) return null;
  if (/\b(\d+|one|two|three|four|five|six|eight|ten|twelve|fifteen|twenty)\s*(?:-|\s)?(?:page|pages|pp)\b/i.test(f))
    return "a page limit";
  if (/\bpage\s*(?:limit|count|maximum|max)\b|\bno\s+more\s+than\s+\d+\s*pages?\b/i.test(f))
    return "a page limit";
  if (/\b(\d+|one|two|three|four|five|six)\s*(?:-|\s)?(?:copies|copy|hard copies|originals?)\b/i.test(f))
    return "a required number of copies";
  if (/\bfont\b|\b\d+\s*(?:-|\s)?point\b|\bmargins?\b|\bspac(?:ing|ed)\b|\btimes new roman\b|\barial\b/i.test(f))
    return "typography or spacing rules";
  if (/\bexcel\b|\.xlsx?\b|\bspreadsheet\b|\bword\b|\.docx?\b|\bnative format\b|\bfillable\b/i.test(f))
    return "a required file format we do not produce";
  if (/\btab(?:bed|s)\b|\bbinder\b|\bsealed\b|\bwet\s*(?:-|\s)?ink\b|\bnotariz/i.test(f))
    return "physical assembly rules";
  return null;
}

/**
 * Apply the format rule to a resolved requirement. An item the platform
 * considered done stops being done, because "done" would mean the generated
 * file already meets a rule nothing has checked. Items that already need a
 * person just carry the rule in their note.
 */
function withFormatConstraint(r: ResolvedRequirement): ResolvedRequirement {
  const rule = unmetFormatRule(r.format);
  if (!rule || r.operator_confirmed) return r;
  const quoted = `The solicitation sets ${rule} for this item: "${r.format}". Check the document against it and mark this complete.`;
  if (r.status === "satisfied") {
    return { ...r, status: "needs_operator", note: quoted };
  }
  return { ...r, note: r.note ? `${r.note} ${quoted}` : quoted };
}

export function resolveRequirements(
  requirements: ComplianceRequirement[],
  ctx: ResolveContext
): ResolvedRequirement[] {
  /**
   * A generated document can stand in for exactly one requirement.
   *
   * Two requirements that map to the same artifact used to be marked
   * satisfied by the same file, and the manifest then named that one PDF
   * twice: a package could contain byte-identical capability statements
   * called "Certificate of insurance" and "State contractor license". The
   * first claimant keeps the document; anything after it is the operator's to
   * supply, which is the truth.
   */
  const claimed = new Set<string>();
  return requirements.map((req) => withFormatConstraint(resolveOne(req, ctx, claimed)));
}

function resolveOne(
  req: ComplianceRequirement,
  ctx: ResolveContext,
  claimed: Set<string>
): ResolvedRequirement {
  if (requirementKeys(req).some((k) => ctx.confirmed.has(k))) {
    return {
      ...req,
      status: "satisfied",
      operator_confirmed: true,
      artifact_kind: artifactFor(req) || undefined,
    };
  }
  const kind = artifactFor(req);
  if (kind && claimed.has(kind) && !req.official_form) {
    return {
      ...req,
      status: "needs_operator",
      note: `Another requirement already uses the generated ${kind.replace(/_/g, " ")}, so this one needs a document from you.`,
    };
  }
  if (kind) claimed.add(kind);

  // A required SPECIFIC agency form cannot be reproduced exactly, the
  // operator must complete the official form. Any generated document is only
  // a worksheet. This is always the operator's item until confirmed.
  if (req.official_form) {
    return {
      ...req,
      status: "needs_operator",
      artifact_kind: artifactFor(req) || undefined,
      note: `Use the official ${req.official_form}${
        req.signature_required ? " and sign it" : ""
      } from the solicitation, the generated draft is a worksheet only.`,
    };
  }
  /**
   * A signature can only be made by a person.
   *
   * The switch below treats "we generated it" and "we filled it from the
   * profile" as satisfied, which is right for a document nobody has to sign.
   * But the solicitation having said this item must be SIGNED is a fact
   * about the item, not about who produced it: reps and certs are prefilled
   * from the profile and still certified under penalty, and a generated
   * cover letter can still require the offeror's signature. Before this,
   * such an item was marked satisfied and went out unsigned, which is
   * non-responsive, and nothing in the package ever asked anyone to sign it.
   *
   * So the signature outranks the satisfier. The generated artifact is still
   * attached (that is what the operator signs), and an operator confirmation
   * above still closes it.
   */
  if (req.signature_required) {
    return {
      ...req,
      status: "needs_signature",
      artifact_kind: artifactFor(req) || undefined,
      note: "The solicitation requires this to be signed. Review the prefilled document, sign it, then mark it complete.",
    };
  }
  switch (req.satisfied_by) {
    case "auto_generated":
    case "from_profile":
      // Only if there is actually a document to produce. The model calls a
      // technical volume, an insurance certificate or a bonding letter
      // "auto_generated" often enough, and with no artifact behind it the
      // item validated as satisfied while the package contained nothing for
      // it: the existence check below skips items with no artifact_kind, so
      // there was no file to find missing.
      if (!kind) {
        return {
          ...req,
          status: "needs_operator",
          note:
            req.instructions ??
            "This is not a document the platform can produce. Upload it, then mark it complete.",
        };
      }
      return { ...req, status: "satisfied", artifact_kind: kind };
    case "operator_signature":
      return {
        ...req,
        status: "needs_signature",
        artifact_kind: artifactFor(req) || undefined,
        note: "Prefilled, review and sign, then mark complete.",
      };
    case "operator_provided":
    default:
      return {
        ...req,
        status: "needs_operator",
        note: req.instructions ?? "You must supply this item.",
      };
  }
}

/** Federal-style submission order by category. */
const CATEGORY_ORDER: RequirementCategory[] = [
  "narrative", // cover/transmittal letter, technical approach
  "form", // signed offer form (SF-1449, etc.)
  "pricing", // pricing/bid schedule
  "certification", // reps & certs
  "acknowledgment", // amendment acknowledgments
  "attachment", // supporting docs
  "other",
];

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 40);
}

function extFor(kind?: string): string {
  return kind ? "pdf" : "";
}

export function buildManifest(
  resolved: ResolvedRequirement[],
  solNumber?: string | null
): PackageItem[] {
  const sorted = [...resolved].sort(
    (a, b) => CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category)
  );
  const solTag = solNumber ? `_${slugify(solNumber)}` : "";

  /**
   * The priced offer itself leads the package.
   *
   * artifactFor can only return the five requirement-shaped kinds, so nothing
   * ever mapped a requirement to the bid PDF, and the manifest is what the
   * download route zips. The document containing the price, the line items and
   * the technical narrative was therefore generated, stored, and blocked on if
   * missing, but never actually placed in the package the operator submits.
   * It is not tied to any one requirement, so it is added here rather than
   * through the resolver.
   */
  const items: PackageItem[] = [
    {
      order: 1,
      filename: `01_bid${solTag}.pdf`,
      requirement_id: "__bid_pdf",
      category: "other",
      source: "generated",
      document_kind: ARTIFACT_KIND.bidPdf,
      status: "satisfied",
    },
  ];

  return items.concat(
    sorted.map((r, i) => {
      const order = i + 2;
      const num = String(order).padStart(2, "0");
      // When the real agency form was found in the attachments, that file IS
      // the package item (the operator signs the actual form).
      if (r.official_form_doc) {
        return {
          order,
          filename: `${num}_${slugify(r.official_form ?? r.title)}${solTag}.pdf`,
          requirement_id: r.id,
          category: r.category,
          source: "solicitation" as const,
          document_path: r.official_form_doc.path,
          status: r.status,
        };
      }
      const ext = extFor(r.artifact_kind);
      const source: PackageItem["source"] =
        r.satisfied_by === "operator_provided"
          ? "operator"
          : r.artifact_kind
            ? "generated"
            : "operator";
      const filename = ext
        ? `${num}_${slugify(r.title)}${solTag}.${ext}`
        : `${num}_${slugify(r.title)}${solTag}__PROVIDE_THIS.txt`;
      return {
        order,
        filename,
        requirement_id: r.id,
        category: r.category,
        source,
        document_kind: r.artifact_kind,
        status: r.status,
      };
    })
  );
}

export interface ValidationInput {
  resolved: ResolvedRequirement[];
  hasIdentifiers: boolean;
  /** Pricing sanity: does bid_amount reconcile with subtotal + markup? */
  pricingReconciles: boolean;
  bidAmount: number | null;
  nowIso: string;
  /**
   * documents.kind values actually stored for this opportunity. When provided,
   * a requirement "satisfied" by a generated artifact whose file was never
   * written (e.g. document assembly failed mid-build) becomes a blocker
   * instead of silently shipping an incomplete package.
   */
  presentDocKinds?: Set<string> | null;
}

export function validatePackage(input: ValidationInput): PackageValidation {
  const blockers: string[] = [];
  const warnings: string[] = [];
  const mandatory = input.resolved.filter((r) => r.mandatory);

  /**
   * No requirements at all is NOT an empty to-do list, it is a missing one.
   *
   * Every real solicitation asks for something: a signed offer form, a price,
   * reps and certs. So an empty matrix never means "this one needs nothing",
   * it means the analysis has not run, could not read the documents (a scanned
   * PDF), or returned nothing usable. Before this check, that state produced
   * an EMPTY package that validated as passed and displayed as ready to
   * submit: every mandatory loop below iterates zero items, so nothing objects.
   * The operator would send a package containing none of the forms the agency
   * asked for and be found non-responsive.
   *
   * Absence of evidence is not evidence of absence, so this fails closed.
   */
  if (input.resolved.length === 0) {
    blockers.push(
      "The submission requirements for this solicitation have not been extracted, so there is no way to know what the package must contain. Re-run the analysis on this opportunity, and if its documents are scans with no readable text, add the required items by hand before submitting."
    );
  }

  for (const r of mandatory) {
    if (r.status === "satisfied") continue;
    if (r.status === "needs_signature") {
      blockers.push(`Sign "${r.title}" (prefilled), then mark it complete.`);
    } else if (r.status === "needs_operator") {
      blockers.push(`Provide "${r.title}": ${r.instructions ?? "required item"}.`);
    } else {
      blockers.push(`Missing required item: "${r.title}".`);
    }
  }

  // Generated-artifact existence: "satisfied by a generated document" only
  // counts if that document actually exists in storage. Operator-confirmed
  // items are exempt (the human vouched for them), as are items backed by an
  // official solicitation file (already stored with the solicitation).
  if (input.presentDocKinds) {
    for (const r of mandatory) {
      if (r.status !== "satisfied" || r.operator_confirmed || r.official_form_doc) continue;
      if (r.artifact_kind && !input.presentDocKinds.has(r.artifact_kind)) {
        blockers.push(
          `The generated document for "${r.title}" (${r.artifact_kind.replace(/_/g, " ")}) is missing from storage. Re-run the Bid Builder.`
        );
      }
    }
    if (!input.presentDocKinds.has(ARTIFACT_KIND.bidPdf)) {
      blockers.push("The bid PDF is missing from storage. Re-run the Bid Builder.");
    }
  }

  for (const r of input.resolved.filter((r) => !r.mandatory)) {
    if (r.status !== "satisfied") {
      warnings.push(`Optional item not included: "${r.title}".`);
    }
  }

  if (input.bidAmount == null || !(input.bidAmount > 0)) {
    blockers.push("Bid price is not set. Enter subcontractor quotes so the bid can be priced.");
  }
  if (!input.pricingReconciles) {
    warnings.push("Pricing total does not reconcile with the line items, review the numbers.");
  }
  if (!input.hasIdentifiers) {
    warnings.push(
      "Company UEI/CAGE is missing from your profile; reps & certs will be incomplete until added."
    );
  }

  const satisfied_count = input.resolved.filter((r) => r.status === "satisfied").length;

  return {
    passed: blockers.length === 0,
    checked_at: input.nowIso,
    blockers,
    warnings,
    satisfied_count,
    total_mandatory: mandatory.length,
  };
}

/** Unresolved (unacknowledged) blocker findings from the independent audit. */
export function openAuditBlockers(findings: AuditFinding[] | null | undefined): AuditFinding[] {
  return (findings ?? []).filter((f) => f.severity === "blocker" && !f.acknowledged);
}

/**
 * The single source of truth for "can this be submitted": the deterministic
 * validation must pass AND the independent audit must have no open blockers.
 */
export function computeReady(
  validation: PackageValidation | null,
  findings: AuditFinding[] | null | undefined
): boolean {
  return Boolean(validation?.passed) && openAuditBlockers(findings).length === 0;
}
